version: '3.8'

services:
  clickhouse-server:
    image: harbor.socmap.net/ops/clickhouse-server:24.2.3.70 
    container_name: clickhouse-server
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
      - ./clickhouse_logs:/var/log/clickhouse-server
      - ./clickhouse_config:/etc/clickhouse-server
    restart: always